{{- if .Values.wrongsecretsCleanup.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wrongsecrets-cleaner
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
{{- end }}
