apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrongsecrets-balancer
  labels:
    app: wrongsecrets-balancer
    {{- include "wrongsecrets-ctf-party.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.balancer.replicas }}
  selector:
    matchLabels:
      {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/secret.yaml") . | sha256sum }}
      labels:
        app: wrongsecrets-balancer
        {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wrongsecrets-balancer
      {{- if .Values.balancer.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.balancer.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.balancer.repository }}:{{ .Values.balancer.tag | default (printf "v%s" .Chart.Version) }}'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.balancer.containerPort }}
          {{- if .Values.balancer.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.balancer.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.balancer.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.balancer.readinessProbe | nindent 12 }}
          {{- end }}
          env:
            {{- range $k, $v := .Values.balancer.env}}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: WRONGSECRETS_TAG
              value: {{ .Values.wrongsecrets.tag}}
            - name: WRONGSECRETS_DESKTOP_TAG
              value: {{ .Values.virtualdesktop.tag }}
            - name: COOKIEPARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: cookieParserSecret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: adminPassword
          {{- if .Values.balancer.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.balancer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.balancer.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.balancer.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.balancer.resources | nindent 12 }}
      {{- if .Values.balancer.volumes }}
      volumes:
        {{- toYaml .Values.balancer.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
