apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
rules:
  - apiGroups: ['apps']
    resources: ['deployment', 'deployments']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'list', 'create', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pod', 'pods', 'pods/log']
    verbs: ['create', 'get', 'list', 'delete', 'watch']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['namespaces']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['configmaps']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['secrets']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'update']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roles']
    verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch', 'admin', 'escalate']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['rolebindings']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'grant', 'bind', 'escalate']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roleRef']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'grant', 'escalate']
  - apiGroups: ['secrets-store.csi.x-k8s.io']
    resources: ['secretproviderclasses']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['networking.k8s.io']
    resources: ['networkpolicies']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['endpoints']
    verbs: [ 'get', 'list']
