apiVersion: v1
kind: ConfigMap
metadata:
  name: wrongsecrets-config
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
data:
  wrongsecrets-ctf-party.yaml: |-
{{ .Values.wrongsecrets.config | indent 4 }}
