apiVersion: v1
kind: Service
metadata:
  namespace: ctfd
  name: ctfd
  labels:
    app: ctfd
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: ctfd
