# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: default
#   name: grafana
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # cert-manager.io/issue-temporary-certificate: "true"
# spec:
#   rules:
#     - host: grafana.<your domain>
#     - http:
#         paths:
#           - path: /grafana
#             pathType: Prefix
#             backend:
#               service:
#                 name: wrongsecrets-grafana
#                 port:
#                   number: 80
